import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import iframePages from "../data/iframes";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl">Pages from file: </h1>
      <ul>
        {iframePages.map((iframePage) => (
          <li
            className="text-blue-600 hover:text-blue-800 underline transition-colors w-min"
            key={iframePage.url}
          >
            <Link href={`embed/${iframePage.url}`}>{iframePage.url}</Link>
          </li>
        ))}
      </ul>
    </>
  );
};

export default Home;
