import type { NextPage, GetStaticPropsContext } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage<{ jsonPageData: JsonPageData }> = ({ jsonPageData }) => {
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className="text-blue-600 hover:text-blue-800 underline transition-colors w-min">
        <Link href={`/`}>Back home</Link>
      </span>

      <main className="mt-20">
        Data this page got from the file:
        <pre>{JSON.stringify(jsonPageData, null, 2)}</pre>
      </main>
    </>
  );
};

import iframePages from "../../data/iframes";
type JsonPageData = typeof iframePages[0];

export async function getStaticPaths() {
  return {
    paths: iframePages.map((iframePage) => ({
      params: { slug: iframePage.url },
    })),
    fallback: false,
  };
}

export async function getStaticProps(context: GetStaticPropsContext) {
  const jsonPageData = iframePages.find(
    (iframePage) => iframePage.url == context.params?.slug
  );
  if (!jsonPageData) {
    console.log(
      `Couldn't find page data for ${context.params?.slug} in iframePages`
    );
  }
  return {
    // Passed to the page component as props
    props: { jsonPageData: jsonPageData },
  };
}

export default Home;
